name: Select random tag and post it on Twitter

on:
  schedule:
    - cron: '32 0,*/3 * * *' # Run every 3 hours at minute 32

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # Checkout the repo content so the runner can access the tags.py file

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # Main.py program itself
        env:
          API_key: ${{ secrets.API_KEY }}
          API_key_secret: ${{ secrets.API_KEY_SECRET }}
          Bearer_token: ${{ secrets.BEARER_TOKEN }}
          Access_Token: ${{ secrets.ACCESS_TOKEN }}
          Access_Token_Secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BSKY_HANDLE: ${{secrets.BSKY_HANDLE}}
          BSKY_PASSWORD: ${{secrets.BSKY_PASSWORD}}
        run: python main.py